# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.boot_timeout = 1200
  config.vm.hostname = "ansible-vm"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.synced_folder ".", "/vagrant"

  # Instalar Ansible
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y ansible
  SHELL

  # Ejecutar playbook
  config.vm.provision "shell", inline: <<-SHELL
    cd /vagrant
    ansible-playbook -i inventories/vagrant/hosts.ini desplegar_app.yml
  SHELL
end
